### ISSUE TITLE
No-op when clicking vertical "..." during Space migration

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1639]
Repro was with Brim commit 89a053b on macOS using scratch artifact \[https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-89a053b9.0/macos/Brim-0.25.0-prerelease-89a053b9.0.dmg.](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-89a053b9.0/macos/Brim-0.25.0-prerelease-89a053b9.0.dmg.)

Before the start of the attached video, I've already had an install of GA Brim tagged `v0.24.0` with Space data in it. The video picks up where I've launched into the newer version of Brim at commit 89a053b and I accept the prompt to migrate my Spaces. When I click the vertical "..." while migration is ongoing, nothing seems to happen.

https://user-images.githubusercontent.com/5934157/118176109-d78a9b80-b3e5-11eb-841c-a6d8112ba9bb.mp4

As you can see, DevTools shows an error:

```
electron/js2c/renderer_init.js:83 Uncaught Error: Could not call remote method 'popup'. Check that the method signature is correct. Underlying error: Error processing argument at index 1, conversion failure from 
Underlying stack: TypeError: Error processing argument at index 1, conversion failure from 
    at Object.a.popup (electron/js2c/browser_init.js:81:3099)
    at electron/js2c/browser_init.js:213:8594
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4973)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9577)
    at Object.emit (events.js:315:20)

    at electron/js2c/browser_init.js:213:8622
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4973)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9577)
    at Object.emit (events.js:315:20)
```

**Comment by philrz** [comment]
Verified in Brim commit 43b0ed5 via nightly macOS build [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-43b0ed51.0/macos/Brim-0.25.0-prerelease-43b0ed51.0.dmg.](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-43b0ed51.0/macos/Brim-0.25.0-prerelease-43b0ed51.0.dmg).

As shown in the attached video, now clicking the vertical "..." reveals a clickable "Cancel" option that did not appear before.

https://user-images.githubusercontent.com/5934157/118415926-f301da80-b661-11eb-8e46-68394f970d96.mp4

Thanks @jameskerr!
