### ISSUE TITLE
"TypeError: Cannot convert undefined or null to object" when opening new window

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1653]
Repro is on Brim commit 207cb69 via scratch build [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-207cb691.0/macos/Brim-0.25.0-prerelease-207cb691.0.dmg](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-207cb691.0/macos/Brim-0.25.0-prerelease-207cb691.0.dmg).

If I bring up the app "fresh" and then immediately select **File > New Window** from the pull-down, I get a crash dump:

```
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at /Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/components/Preferences/usePreferencesForm.js:39:12
    at Array.forEach (<anonymous>)
    at useConfigsForm (/Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/components/Preferences/usePreferencesForm.js:38:11)
    at Preferences (/Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/components/Preferences/Preferences.js:117:60)
    at renderWithHooks (/Applications/Brim.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:14803:18)
    at updateFunctionComponent (/Applications/Brim.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17034:20)
    at beginWork (/Applications/Brim.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18610:16)
    at HTMLUnknownElement.callCallback (/Applications/Brim.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (/Applications/Brim.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:237:16)
```

https://user-images.githubusercontent.com/5934157/118677003-bd1f3c00-b7b0-11eb-9e33-119a722efa63.mp4

**Comment by philrz** [comment]
Verified in Brim commit 7a6064d on macOS using scratch artifact [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-7a6064df.0/macos/Brim-0.25.0-prerelease-7a6064df.0.dmg](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-7a6064df.0/macos/Brim-0.25.0-prerelease-7a6064df.0.dmg).

Now when I select **File > New Window**, there's no longer a crash dump.

https://user-images.githubusercontent.com/5934157/118842192-d641ee80-b87d-11eb-9512-5478bd5b66c0.mp4

Thanks @mason-fish!
