### ISSUE TITLE
"TypeError: this.r.get(...).toDate is not a function" when opening Log Detail on unshaped NDJSON

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1660]
Repro is with Brim commit 85fb455.

If I drag test data file [https://github.com/brimdata/brim/blob/main/itest/testdata/sample.ndjson](https://github.com/brimdata/brim/blob/main/itest/testdata/sample.ndjson) into Brim and then double-click a `conn` record, the Log Detail window that opens is populated with a crash:

```
TypeError: this.r.get(...).toDate is not a function
    at ZeekEvent.getTime (/Users/phil/work/brim/dist/ppl/detail/models/ZeekEvent.js:29:31)
    at UidPanel (/Users/phil/work/brim/dist/ppl/detail/Correlation.js:85:82)
    at renderWithHooks (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:14803:18)
    at updateFunctionComponent (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:17034:20)
    at updateSimpleMemoComponent (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:16972:10)
    at beginWork (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:18687:16)
    at HTMLUnknownElement.callCallback (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at beginWork$1 (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
```

**Comment by philrz** [comment]
Verified in Brim commit 34eef53.

As shown in the attached video, now when I import the same test file I can double-click `conn` records to see them in the Log Detail view without error.

https://user-images.githubusercontent.com/5934157/119045431-50eb3680-b970-11eb-81fd-b6e3ab62ecbc.mp4

Thanks @jameskerr!
