### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1703]
Repro is with Brim commit 781f521.

I start by importing test pcap [https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz](https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz) (after uncompressing). I've only managed to reproduce the problem with Suricata alerts. As the attached video shows, after the import completes, I isolate the Suricata records by filtering `event_type=="alert"` and then start single-clicking on the records one at a time while the Log Detail panel is open. Eventually I hit one that causes the following dump to appear:

```
TypeError: Cannot read property 'startsWith' of undefined
    at Link (/Users/phil/work/brim/dist/src/js/components/common/Link.js:19:12)
    at renderWithHooks (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:14803:18)
    at mountIndeterminateComponent (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:17482:13)
    at beginWork (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:18596:16)
    at HTMLUnknownElement.callCallback (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at beginWork$1 (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:23203:7)
    at performUnitOfWork (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:22157:12)
    at workLoopSync (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:22130:22)
```

https://user-images.githubusercontent.com/5934157/121241593-78873d80-c850-11eb-9ff1-2f861639f7b1.mp4

**Comment by philrz** [comment]
Verified in Brim commit fd23d53.

Repeating the original repro steps, now I can click through an entire page of `alert` events with the Log Detail panel open and not see an error, whereas before I consistently saw the error after clicking just a handful.

https://user-images.githubusercontent.com/5934157/121601908-6a295500-c9fb-11eb-9f02-0f26956f4fa7.mp4

Thanks @mason-fish!
