### ISSUE TITLE
"Error: Invalid relTime expression" when requesting recent data on unshaped NDJSON

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1769]
Repro is with Brim commit 333e17f via build artifact https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-333e17fc.0/macos/Brim-0.25.0-prerelease-333e17fc.0.dmg.

To repro:

1. Drag & drop the [NDJSON Zeek zed-sample-data](https://github.com/brimdata/zed-sample-data/tree/main/zeek-ndjson) into the app
2. Select "Last 30 minute of pool" from the time drop down

https://user-images.githubusercontent.com/5934157/128721239-2206e133-6bac-41cf-b5e6-d28218412e0d.mp4

As shown in the attached video, this crashes the app with this error dump:

```
Error: Invalid relTime expression: -1800.1000000
    at parse (/Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/brim/relTime.js:37:11)
    at Object.toTs (/Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/brim/relTime.js:62:22)
    at computeArg (/Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/brim/span.js:33:71)
    at compute (/Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/brim/span.js:38:13)
    at Object.span (/Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/brim/span.js:29:18)
    at /Applications/Brim.app/Contents/Resources/app.asar/dist/app/search/flows/initial-viewer-search.js:45:50
    at /Applications/Brim.app/Contents/Resources/app.asar/node_modules/redux-thunk/lib/index.js:11:18
    at /Applications/Brim.app/Contents/Resources/app.asar/dist/src/js/components/SearchResults/SearchResults.js:36:5
    at commitHookEffectListMount (/Applications/Brim.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19731:26)
    at commitLifeCycles (/Applications/Brim.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:19787:9)
```

**Comment by jameskerr** [comment]
Thanks for filing Phil. I'll write a test and a fix for that.

**Comment by philrz** [comment]
Verified in Brim commit 2e3c791.

As shown in the attached video, now when we import the same unshaped NDJSON and select "Last 30 minute of pool" from the time drop down, the app no longer crashes. Instead an error message from the backend (which is admittedly somewhat opaque) is passed through, and the time pickers get set to what are effectively garbage values. All that said, this is an improvement over an app crash, and as @jameskerr notes in #1777, there's more we can do here, which will surely be picked up after we ship this next GA release and are doing more designs related to importing data sources that may have arbitrary Pool keys.

https://user-images.githubusercontent.com/5934157/130149696-6be0f117-cb81-4b86-9f55-1ef075d79904.mp4

Thanks @jameskerr!
