### ISSUE TITLE
TypeError: Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2437]
Repro is with Brim commit 951f321d.

Like #2416, this issue can be reproduced with test data [sample.zng](https://github.com/brimdata/brim/blob/main/src/test/shared/data/sample.zng) from the Brim repo.

As shown in the attached video, when the Detail panel is open, certain records (such as the first Zeek `files` record in [sample.zng](https://github.com/brimdata/brim/blob/main/src/test/shared/data/sample.zng)) cause an error dump.

https://user-images.githubusercontent.com/5934157/179086732-68845186-653f-4eb9-b6f1-55dc1edb2fe7.mp4

The error dump:

```
TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at sortBy (/Users/phil/work/brim/dist/ppl/detail/util/sort.js:14:10)
    at Object.sort (/Users/phil/work/brim/dist/ppl/detail/util/sort.js:9:20)
    at /Users/phil/work/brim/dist/ppl/detail/UidPanel.js:55:27
    at updateMemo (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:17078:19)
    at Object.useMemo (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:17733:16)
    at Object.useMemo (/Users/phil/work/brim/node_modules/react/cjs/react.development.js:1645:21)
    at UidPanel (/Users/phil/work/brim/dist/ppl/detail/UidPanel.js:54:32)
    at renderWithHooks (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:16141:18)
    at updateFunctionComponent (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:20313:20)
```

**Comment by philrz** [comment]
Verified in Brim commit 655ec4b.

As shown in the attached video, now I can click through all the records in the first screen of test data (including the specific one that first triggered the error dump before) without any problems in the Detail panel.

https://user-images.githubusercontent.com/5934157/179096906-180d0209-0941-4351-8214-630a1cfee6ef.mp4

Thanks @mason-fish!
