### ISSUE TITLE
"TypeError: r?.try is not a function" after executing query

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2460]
Repro is with Brim commit 7ba79d8. This issue was found by @mccanne during a demo.

Repro steps shown in the attached video:
1. Launch the app
2. Import the [sample.zng](https://github.com/brimdata/brim/blob/main/src/test/shared/data/sample.zng) test data from this repo
3. Execute the query `sample | yield id`

A stack dump is produced.

https://user-images.githubusercontent.com/5934157/180854153-2fea6cfa-fea1-4a67-abc3-c8fff7766a84.mp4

The stack dump:

```
TypeError: r?.try is not a function
    at /Users/phil/work/brim/dist/js/models/TableColumns.js:25:36
    at Array.forEach (<anonymous>)
    at /Users/phil/work/brim/dist/js/models/TableColumns.js:24:21
    at Array.forEach (<anonymous>)
    at TableColumns.setWidths (/Users/phil/work/brim/dist/js/models/TableColumns.js:20:19)
    at /Users/phil/work/brim/dist/js/state/Columns/selectors.js:24:11
    at /Users/phil/work/brim/node_modules/reselect/lib/index.js:76:25
    at /Users/phil/work/brim/node_modules/reselect/lib/index.js:36:25
    at /Users/phil/work/brim/node_modules/reselect/lib/index.js:90:33
    at /Users/phil/work/brim/node_modules/reselect/lib/index.js:36:25
```

**Comment by philrz** [comment]
I noticed this top-level error message is similar to the one shown in #2333, but the stack dump looks very different so I've opened this as a separate issue.

**Comment by philrz** [comment]
Verified in Zui commit a20f709.

Repeating the repro steps as shown in the attached video, now when we execute the `sample | yield id` query there's no longer a stack dump.

https://user-images.githubusercontent.com/5934157/183527995-4d0144a7-e1a4-47fa-a2df-e9056d71b3e2.mp4

Thanks @jameskerr!
