### ISSUE TITLE
"Uncaught TypeError: s.pins.push is not a function" when using imported query

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2488]
Repro is with Brim commit 1ee21a8.

Steps as shown in the attached video:

1. Import the `Brim.json` that represents the exported query folder from GA Brim tagged `v0.31.0`.
2. Import a pcap, such as the [sample.pcap](https://github.com/brimdata/brim/blob/main/src/test/shared/data/sample.pcap) from this repo.
3. Click **Query Pool**
4. Click the **Unique DNS Queries** from the library
5. Observe the "pool name is missing" error, which is expected since queries in the old app experienced lacked these (see #2478)
6. Attempt to click **Pins > New 'From' Pin** in an attempt to correct this

As the repro shows, rather than adding the pin, nothing happens.

https://user-images.githubusercontent.com/5934157/184780648-2a1d1883-06a4-45ff-8b59-d3bbc0e7e5af.mp4

Here's the error dump that appears in DevTools at that point:

```
/Users/phil/work/brim/dist/js/state/Editor/reducer.js:43 Uncaught TypeError: s.pins.push is not a function
    at addPin (/Users/phil/work/brim/dist/js/state/Editor/reducer.js:43)
    at createReducer.ts:247
    at Immer.produce (immerClass.ts:96)
    at createReducer.ts:246
    at Array.reduce (<anonymous>)
    at createReducer.ts:213
    at Object.combination [as default] (/Users/phil/work/brim/node_modules/redux/lib/redux.js:465)
    at /Users/phil/work/brim/dist/js/state/Tabs/reducer.js:100
    at createReducer.ts:247
    at Immer.produce (immerClass.ts:96)
```

Not sure if it's related, but before that dump, there also were several dumps of the form:

```
pool name missing 
    at ResultsError (/Users/phil/work/brim/dist/app/query-home/results/results-error.js:28:28)
    at div
    at I (/Users/phil/work/brim/node_modules/styled-components/dist/styled-components.cjs.js:1:19375)
    at AppErrorBoundary (/Users/phil/work/brim/dist/js/components/AppErrorBoundary.js:34:9)
    at div
    at I (/Users/phil/work/brim/node_modules/styled-components/dist/styled-components.cjs.js:1:19375)
    at ResultsComponent (/Users/phil/work/brim/dist/app/query-home/results/index.js:56:33)
    at div
    at I (/Users/phil/work/brim/node_modules/styled-components/dist/styled-components.cjs.js:1:19375)
    at div
    at I (/Users/phil/work/brim/node_modules/styled-components/dist/styled-components.cjs.js:1:19375)
    at QueryHome (/Users/phil/work/brim/dist/app/query-home/index.js:37:36)
    at QueryRoute (/Users/phil/work/brim/dist/app/query-home/route.js:40:39)
    at Route (/Users/phil/work/brim/node_modules/react-router/cjs/react-router.js:464:29)
    at Switch (/Users/phil/work/brim/node_modules/react-router/cjs/react-router.js:666:29)
    at InitLake (/Users/phil/work/brim/dist/app/lakes/root.js:72:21)
    at LakeRoot (/Users/phil/work/brim/dist/app/lakes/root.js:24:37)
    at main
    at I (/Users/phil/work/brim/node_modules/styled-components/dist/styled-components.cjs.js:1:19375)
    at MainArea (/Users/phil/work/brim/dist/app/routes/app-wrapper/main-area.js:33:21)
    at div
    at I (/Users/phil/work/brim/node_modules/styled-components/dist/styled-components.cjs.js:1:19375)
    at AppGrid (/Users/phil/work/brim/dist/app/routes/app-wrapper/app-grid.js:26:20)
    at AppWrapper (/Users/phil/work/brim/dist/app/routes/app-wrapper/app-wrapper.js:14:23)
    at Route (/Users/phil/work/brim/node_modules/react-router/cjs/react-router.js:464:29)
    at Switch (/Users/phil/work/brim/node_modules/react-router/cjs/react-router.js:666:29)
    at TabsRouter (/Users/phil/work/brim/dist/app/router/tabs-router.js:61:9)
    at AppTabsRouter (/Users/phil/work/brim/dist/app/router/app-tabs-router.js:11:26)
    at App (/Users/phil/work/brim/dist/js/components/App.js:21:33)
    at exports.ThemeProvider (/Users/phil/work/brim/node_modules/styled-components/dist/styled-components.cjs.js:1:25072)
    at Provider (/Users/phil/work/brim/node_modules/react-redux/lib/components/Provider.js:19:3)
    at DndProvider (/Users/phil/work/brim/node_modules/react-dnd/dist/cjs/core/DndProvider.js:41:23)
    at AppErrorBoundary (/Users/phil/work/brim/dist/js/components/AppErrorBoundary.js:34:9)
    at BrimProvider (/Users/phil/work/brim/dist/app/core/context.js:47:17)
```

**Comment by jameskerr** [comment]
Aww shoot. Thanks @philrz
