### ISSUE TITLE
"TypeError: Cannot read properties of null (reading 'map')" when clicking pool with unspecified layout

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2490]
Repro is with Brim commit 1ee21a8.

It's currently possible to create a pool without specifying the layout (i.e., key/order). When such a pool is clicked in the app, it produces a stack dump.

https://user-images.githubusercontent.com/5934157/184940027-bedfa3e1-89e5-4e25-affc-ecabbafc0445.mp4

```
TypeError: Cannot read properties of null (reading 'map')
    at PoolHome (/Users/phil/work/brim/dist/app/pools/home.js:63:40)
    at renderWithHooks (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:16141:18)
    at mountIndeterminateComponent (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:20838:13)
    at beginWork (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:22342:16)
    at beginWork$1 (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:27219:14)
    at performUnitOfWork (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:26392:12)
    at workLoopSync (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:26303:5)
    at renderRootSync (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:26271:7)
    at recoverFromConcurrentError (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:25689:20)
    at performSyncWorkOnRoot (/Users/phil/work/brim/node_modules/react-dom/cjs/react-dom.development.js:25935:20)
```

**Comment by philrz** [comment]
Verified in Brim commit eac277e.

As shown in the attached video, now we can click on the pool with the null key and no longer see a stack dump.

https://user-images.githubusercontent.com/5934157/184978028-1513f53b-2b44-419d-a625-f5be5ac191ba.mp4

Thanks @jameskerr
