### ISSUE TITLE
App can't start if it was previously closed with an open About window

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2527]
Repro is with Brim commit a3b32bd. A community user originally reported this symptom in the course of normal app use.

As shown in the attached video, the problem can be reproduced by having an **About** window left open when exiting the app. When relaunching, the app window never appears, and instead the following stack trace appears in the log:

```
11:08:54.438 › TypeError: Cannot read properties of undefined (reading 'lakes')
    at getPersistedLakes (/Users/phil/work/brim/dist/js/state/stores/get-persistable.js:72:16)
    at Object.getPersistedWindowState (/Users/phil/work/brim/dist/js/state/stores/get-persistable.js:49:12)
    at Object.decodeSessionState (/Users/phil/work/brim/dist/js/electron/session-state.js:37:53)
    at Function.boot (/Users/phil/work/brim/dist/js/electron/brim.js:55:41)
    at async Object.boot (/Users/phil/work/brim/dist/js/electron/run-main/boot.js:12:18)
    at async Object.main (/Users/phil/work/brim/dist/js/electron/run-main/run-main.js:26:18)
(node:89119) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'lakes')
    at getPersistedLakes (/Users/phil/work/brim/dist/js/state/stores/get-persistable.js:72:16)
    at Object.getPersistedWindowState (/Users/phil/work/brim/dist/js/state/stores/get-persistable.js:49:12)
    at Object.decodeSessionState (/Users/phil/work/brim/dist/js/electron/session-state.js:37:53)
    at Function.boot (/Users/phil/work/brim/dist/js/electron/brim.js:55:41)
    at async Object.boot (/Users/phil/work/brim/dist/js/electron/run-main/boot.js:12:18)
    at async Object.main (/Users/phil/work/brim/dist/js/electron/run-main/run-main.js:26:18)
```

https://user-images.githubusercontent.com/5934157/189416615-bf3415e5-61af-4ac7-9a5f-fb092819fbe8.mp4

**Comment by philrz** [comment]
Verified in Brim commit 9b2c9c4.

I started by getting into the repro state of this issue using commit a3b32bd. I was sure to have a couple pools, some saved queries, and some history that would represent saved state I'd not want to lose. I then exited the app while leaving the **About** window open and tried/failed to restart, seeing the stack dump. At that point I rebuilt at the commit 9b2c9c4 that includes the fix and relaunched. The app then came up without issue and my saved state all seemed to be intact.

https://user-images.githubusercontent.com/5934157/189419168-9a081b84-30e6-4fcd-9dc5-9ed536740a46.mp4

Thanks @jameskerr!
