### ISSUE TITLE
Viewing appState.json causes "TypeError: Cannot read properties of null (reading 'map')"

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#2640]
Repro is with Brim commit 6f4f939.

As shown in the screenshot below, if I load the attached [appState.json.gz](https://github.com/brimdata/brim/files/10522256/appState.json.gz) into the app and try to view it, I'm shown a stack dump.

![image](https://user-images.githubusercontent.com/5934157/215172344-140fd190-cc87-49c8-a47b-51781eedf3fb.png)

The text of the stack dump:

```
TypeError: Cannot read properties of null (reading 'map')
    at Object.createColumns (/Users/phil/work/brim/dist/components/zed-table/create-columns.js:10:28)
    at new ZedColumn (/Users/phil/work/brim/dist/components/zed-table/column.js:123:65)
    at /Users/phil/work/brim/dist/components/zed-table/create-columns.js:10:48
    at Array.map (<anonymous>)
    at Object.createColumns (/Users/phil/work/brim/dist/components/zed-table/create-columns.js:10:28)
    at new ZedColumn (/Users/phil/work/brim/dist/components/zed-table/column.js:123:65)
    at /Users/phil/work/brim/dist/components/zed-table/create-columns.js:10:48
    at Array.map (<anonymous>)
    at Object.createColumns (/Users/phil/work/brim/dist/components/zed-table/create-columns.js:10:28)
    at new ZedColumn (/Users/phil/work/brim/dist/components/zed-table/column.js:123:65)
```

**Comment by philrz** [comment]
Verified in Brim commit 1e0a608.

As shown in the video below, now the file can be viewed after loading without seeing a stack dump.

https://user-images.githubusercontent.com/5934157/216703546-969a7527-729e-4f8c-a199-188662dd9002.mp4

Thanks @jameskerr!
